name: CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['*']

jobs:

    tests:
        name: Tests - PHP ${{ matrix.php }} ${{ matrix.dependency-version }}
        runs-on: ubuntu-latest
        timeout-minutes: 15
        strategy:
            matrix:
                php: [ '8.1', '8.2', '8.3', '8.4' ]
                dependency-version: [ '' ]
                include:
                    -   php: '8.1'
                        dependency-version: '--prefer-lowest'
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
            -   name: Cache Composer dependencies
                uses: actions/cache@v4
                with:
                    path: ~/.composer/cache
                    key: php-${{ matrix.php }}-composer-locked-${{ hashFiles('composer.lock') }}
                    restore-keys: php-${{ matrix.php }}-composer-locked-
            -   name: Install PHP dependencies
                run: composer update ${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress --no-suggest
            -   name: PHPUnit
                run: vendor/bin/phpunit

    cs:
        name: Coding standards
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.3
                    tools: cs2pr
                    coverage: none
            -   name: Cache Composer dependencies
                uses: actions/cache@v4
                with:
                    path: ~/.composer/cache
                    key: php-composer-locked-${{ hashFiles('composer.lock') }}
                    restore-keys: php-composer-locked-
            -   name: Install PHP dependencies
                run: composer install --no-interaction --no-progress --no-suggest
            -   name: PHP CS
                run: vendor/bin/phpcs -q --no-colors --report=checkstyle | cs2pr
            -   name: PHPStan
                run: vendor/bin/phpstan
